projects:
  chathat:
    schemaPath: amplify/backend/api/chathat/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: /graphql
        region: eu-central-1
        apiId: null
        maxDepth: 2
